horizontal-sharding/config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => "/res" if Rails.env.development?
  mount SolidQueueDashboard::Engine, at: "/queue"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resource :tenant, only: [ :show, :create ]
  # Defines the root path route ("/")
  root "tenants#show"
end

horizontal-sharding/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  connects_to database: { writing: :primary, reading: :primary }
end

horizontal-sharding/app/models/shard_record.rb
class ShardRecord < ApplicationRecord
  self.abstract_class = true

  connects_to shards: {
    arkency: { writing: :arkency, reading: :arkency },
    railseventstore: { writing: :railseventstore, reading: :railseventstore }
  }
end

horizontal-sharding/app/models/tenant.rb
class Tenant < ApplicationRecord
  def shard
    self.host.split(".").first.to_sym
  end
end

horizontal-sharding/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

horizontal-sharding/app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  Visit = Data.define(:timestamp, :url, :shard)

  def show
    ActiveRecord::Base.connected_to(role: :reading, shard: :default) do
      @tenant = Tenant.find_by(host: request.host)
    end
    render :invalid and return unless @tenant

    @visits = Rails.configuration.event_store.read.of_type([ VisitRegistered ]).backward.limit(10).map do |fact|
      Visit.new(
        timestamp: fact.timestamp,
        url: [ ruby_event_store_browser_app_path, "events", fact.event_id ].join("/"),
        shard: fact.metadata[:shard]
      )
    end
  end

  def create
    Rails.configuration.event_store.publish(VisitRegistered.new(data: { host: request.host }))
    redirect_to root_path
  end
end

horizontal-sharding/app/helpers/application_helper.rb
module ApplicationHelper
end

horizontal-sharding/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Horizontal Sharding" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="grid min-h-full place-items-center bg-white px-6 py-24 sm:py-32 lg:px-8">
      <div class="text-center">
        <h1 class="mt-4 text-5xl font-semibold tracking-tight text-balance text-gray-900 sm:text-7xl">Tenant: <%= @tenant&.name || "Unrecognized" %></h1>
        <% if @tenant %>
          <p class="mt-6 text-lg font-medium text-pretty text-gray-500 sm:text-xl/8">Last 10 registered visits:</p>
      <% end %>
        <div class="mt-10 flex flex-col items-center justify-center gap-x-6">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

horizontal-sharding/app/views/tenants/invalid.html.erb
<div class="flow-root w-full mb-16">
  <ul role="list" class="-mb-8">
    <% Tenant.all.each do |t| %>
      <a href="http://<%= t.host %>">
        <li>
          <div class="relative pb-8">
              <div class="flex min-w-0 flex-1 justify-between space-x-4 pt-1.5">
                <div>
                  <p class="text-sm text-gray-500">Go to: <span class="font-medium text-gray-900"><%= t.name %></span></p>
                </div>
            </div>
          </div>
        </li>
      </a>
    <% end %>
  </ul>
</div>

horizontal-sharding/app/views/tenants/show.html.erb
<div class="flow-root w-full mb-16">
  <ul role="list" class="-mb-8">
    <% @visits.each do |v| %>
      <a href="<%= v.url %>">
        <li>
          <div class="relative pb-8">
            <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
            <div class="relative flex space-x-3">
              <div>
                <span class="flex size-8 items-center justify-center rounded-full bg-green-500 ring-8 ring-white">
                  <svg class="size-5 text-white" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
                    <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 0 1 .143 1.052l-8 10.5a.75.75 0 0 1-1.127.075l-4.5-4.5a.75.75 0 0 1 1.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 0 1 1.05-.143Z" clip-rule="evenodd" />
                  </svg>
                </span>
              </div>
              <div class="flex min-w-0 flex-1 justify-between space-x-4 pt-1.5">
                <div>
                  <p class="text-sm text-gray-500">Visited: <span class="font-medium text-gray-900"><%= v.shard %></span></p>
                </div>
                <div class="text-right text-sm whitespace-nowrap text-gray-500">
                  <time datetime="<%= v.timestamp.localtime %>"><%= v.timestamp.localtime.to_fs(:long_ordinal) %></time>
                </div>
              </div>
            </div>
          </div>
        </li>
      </a>
    <% end %>
  </ul>
</div>
<%= button_to "Mark as visited", tenant_path, class: "rounded-md bg-lime-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-lime-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-lime-600" %>